# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://ligato.io/
title: Ligato
email: ligato@cisco.com
author: Ligato Team
description: > 
  Ligato is an open source project that provides a platform and code samples for development of cloud native VNFs.
  It includes a VNF agent for VPP (FD.io) and a Service Function Chain (SFC) Controller for stitching virtual and physical networking. 
copyright: 'Copyright &copy; 2018 Ligato community. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable : true

baseurl:

collections:
  docs:
    output: true

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Cloud Native Open Source
# this appears on the top navigation bar next to the home button

site_title: Cloud Native Open Source
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

sidebars:
- mydoc_sidebar
- home_sidebar
- mydoc_net
- docpages_sidebar
- servicepages_sidebar

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: GitHub
    icon: github
    url: https://github.com/ligato

headertitles:

 - title: About
   url: about
   type: scroll
   nonscrolllink: '#about' 

 - title: CN Infra
   url: cn-infra
   type: scroll
   nonscrolllink: '#cn-infra'

 - title: VPP Agent
   url: vpp-agent
   type: scroll
   nonscrolllink: vpp-agent/
   
 - title: SFC Controller
   url: sfc-controller
   type: scroll
   nonscrolllink: sfc-controller/
   
 - title: BGP Agent
   url: bgp-agent
   type: scroll
   nonscrolllink: bgp-agent/


